---
apiVersion: v1
kind: Service
metadata:
  name: fraud-prvt-posdevice-location-service
  namespace: app-prod
  labels:
    app: fraud-prvt-posdevice-location
spec:
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: fraud-prvt-posdevice-location
