---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-anq
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: coureregistry.azurecr.io/fraud-prvt-posdevice-location
    newTag: latest
